### ISSUE TITLE
Timeout when "visit will open new URL based on instance.url"

### ISSUE THREAD

**Issue by gedex** [woocommerce/wp-e2e-page-objects#21]
Sometimes timeout occurs when visiting https://automattic.com/work-with-us/. With Incognito, the page is fully loaded after ~7s. Either increases the mocha timeout or switch to other page with less assets.

Here's the timeout error when happened:

```
TimeoutError: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -0.007
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
      at TimeoutError (node_modules/selenium-webdriver/lib/error.js:342:5)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:639:15)
      at parseHttpResponse (node_modules/selenium-webdriver/http/index.js:538:13)
      at client_.send.then.response (node_modules/selenium-webdriver/http/index.js:472:11)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebDriver.navigate().to(https://automattic.com/work-with-us/)
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:377:17)
      at Navigation.to (node_modules/selenium-webdriver/lib/webdriver.js:1027:25)
      at Driver.get (node_modules/selenium-webdriver/lib/webdriver.js:795:28)
      at Page.visit (src/pages/page.js:62:15)
      at Context.<anonymous> (test/page.js:91:8)
      at node_modules/selenium-webdriver/testing/index.js:144:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1082:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:129:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: Page visit will open new URL based on instance.url
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)
```

**Comment by gedex** [comment]
After investigating, it seems unrelated to page being tested or mocha timeout, instead it comes from chromedriver. Related links with similar issue:

* https://bugs.chromium.org/p/chromedriver/issues/detail?id=402
* https://bugs.chromium.org/p/chromedriver/issues/detail?id=817
* http://sqa.stackexchange.com/questions/9007/how-to-handle-time-out-receiving-message-from-the-renderer-in-chrome-driver

**Comment by gedex** [comment]
Unable to reproduce this after running the test multiple times. Seems intermittent and maybe hiccup from chromedriver.
