### ISSUE TITLE
Sporadic error on "WPAdmin may trigger admin notice after performing some actions"

### ISSUE THREAD

**Issue by gedex** [woocommerce/wp-e2e-page-objects#22]
Error when that happened:

```
2) WPAdmin may trigger admin notice after performing some actions:
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#users_can_register"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
      at NoSuchElementError (node_modules/selenium-webdriver/lib/error.js:242:5)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:639:15)
      at parseHttpResponse (node_modules/selenium-webdriver/http/index.js:538:13)
      at client_.send.then.response (node_modules/selenium-webdriver/http/index.js:472:11)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: WebDriver.findElement(By(css selector, #users_can_register))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:377:17)
      at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:864:17)
      at Object.unsetCheckbox (node_modules/wp-e2e-webdriver/lib/helper.js:96:16)
      at WPAdminSettingsGeneral.checkMembership (src/pages/wp-admin/wp-admin-settings-general.js:36:10)
      at Context.<anonymous> (test/wp-admin/wp-admin.js:321:12)
      at node_modules/selenium-webdriver/testing/index.js:144:19
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1082:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:129:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2896:21)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2820:25)
      at node_modules/selenium-webdriver/lib/promise.js:639:7
  From: Task: WPAdmin may trigger admin notice after performing some actions
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:128:10)
```

**Comment by gedex** [comment]
I couldn't reproduce this locally. Closing.
